export enum EtatDeTournee {
    PLANIFIEE = 'PLANIFIEE',
    ENPARCOURS = 'ENPARCOURS',
    ENCHARGEMENT = 'ENCHARGEMENT',
    ENDECHARGEMMENT = 'ENDECHARGEMMENT',
    ENCLIENTELE = 'ENCLIENTELE',
    ENMONTAGE = 'ENMONTAGE',
    ENRETOUR = 'ENRETOUR',
    EFFECTUEE = 'EFFECTUEE',
}