export enum EtatDeLivraison {
    PLANIFIEE = 'PLANIFIEE',
    ENPARCOURS = 'ENPARCOURS',
    ENDECHARGEMMENT = 'ENDECHARGEMENT',
    ENCLIENTELE = 'ENCLIENTELE',
    ENMONTAGE = 'ENMONTAGE',
    EFFECTUEE = 'EFFECTUEE',
}